### ISSUE TITLE
Newest update causes mod not to work

### ISSUE THREAD

**Issue by Holmium67** [Holmium67/FuckSacrificeRestrictions#2]
Leaving this issue here so people know this is known, something must have changed in the latest Inscryption update, and when I get time, I will fix it.

**Comment by nformis** [comment]
Just a heads up: The mod seems to be working flawlessly on the last version of Inscryption (v1.09).

**Comment by Holmium67** [comment]
> Just a heads up: The mod seems to be working flawlessly on the last version of Inscryption (v1.09).

Thanks for reminding me I need to close this issue lol
